export enum CollocationType {
  NOUN = 'NOUN',
  VERB = 'VERB',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PRONOUN = 'PRONOUN',
  CONJUNCTION = 'CONJUNCTION',
  PREPOSITION = 'PREPOSITION',
  NUMERAL = 'NUMERAL'
}
