export enum FrequencyListSearchType {
  WORDS = 'WORDS',
  LEMMAS = 'LEMMAS',
  NOUNS = 'NOUNS',
  VERBS = 'VERBS',
  ADJECTIVES = 'ADJECTIVES',
  ADVERBS = 'ADVERBS',
  PRONOUNS = 'PRONOUNS',
  CONJUNCTIONS = 'CONJUNCTIONS',
  PREPOSITIONS = 'PREPOSITIONS',
  NUMERALS = 'NUMERALS'
}

export enum FrequencyListSearchFilter {
  ALL = 'ALL',
  STARTING_WITH = 'STARTING_WITH',
  ENDING_WITH = 'ENDING_WITH',
  CONTAINING = 'CONTAINING'
}
